"""TEMPO collective-group D2H checkpoint scheduling prototype."""

from tempo.c0_admission import C0Admission, C0Config, C0Decision, C0Snapshot

from tempo.group_credit_checkpoint import GroupCreditCheckpointer
from tempo.resource_domain import (
    DOMAIN_CONTRACTS,
    DomainContract,
    DomainObservation,
    EvidenceLevel,
    FlowStage,
    ForegroundOperation,
    ResourceDomain,
    allowed_counter_scopes,
    StateFlow,
    aggregate_observations,
    causal_candidate_domains,
    domain_contract,
)
from tempo.tier_attribution import (
    AttributionMode,
    ModeSpec,
    required_domains_for_modes,
    TierEvaluation,
    evaluate_tier_attribution,
    validate_mode_evidence,
    validate_attribution_manifest,
)
from tempo.kv_flow import (
    KVAdmissionDecision,
    KVFlowLedger,
    KVOperation,
    KVTransferRequest,
    KVVersion,
)
from tempo.torch_kv_backend import TorchKVBackend, TorchKVCompletion
from tempo.causal_gate import (
    CausalGateConfig,
    CausalModeRecord,
    CausalPromotion,
    InferenceModeRecord,
    evaluate_causal_matrix,
    evaluate_inference_matrix,
)
from tempo.domain_admission import (
    DomainAdmissionController,
    DomainBudget,
    DomainDecision,
    DomainRequest,
    FlowAdmissionLedger,
)
from tempo.domain_evidence import (
    AtlasEntry,
    CounterSupport,
    DomainEvidence,
    DomainCoverage,
    PathStatus,
    assess_domain_coverage,
    build_atlas,
    controller_candidates,
    detect_bottleneck_shift,
)
from tempo.domain_counters import CounterDelta, CounterSnapshot, counter_delta, validate_counter_series
from tempo.path_intervention import (
    PathInterventionEvidence,
    build_causal_domain_controller,
    controller_ready_domains,
    path_intervention_candidates,
    validate_path_intervention_artifact,
)
from tempo.flow_adapters import (
    StateFlowAdmission,
    checkpoint_state_flow,
    flow_route_signature,
    kv_state_flow,
)
from tempo.replication_gate import (
    InferenceReplicationBlock,
    ReplicationResult,
    TrainingReplicationBlock,
    evaluate_inference_replication,
    evaluate_training_replication,
)
from tempo.foreground_path import validate_foreground_path
from tempo.observation_window import (
    ObservationInterval,
    JoinedObservationWindow,
    canonicalize_observation_windows,
    join_observation_window,
    observation_window_contract,
    serialize_joined_observation_window,
    serialize_observation_interval,
    validate_observation_windows,
)

__version__ = "0.1.0"
__all__ = [
    "C0Admission",
    "C0Config",
    "C0Decision",
    "C0Snapshot",
    "GroupCreditCheckpointer",
    "DOMAIN_CONTRACTS",
    "DomainContract",
    "DomainObservation",
    "EvidenceLevel",
    "FlowStage",
    "ForegroundOperation",
    "ResourceDomain",
    "allowed_counter_scopes",
    "StateFlow",
    "aggregate_observations",
    "causal_candidate_domains",
    "domain_contract",
    "AttributionMode",
    "ModeSpec",
    "required_domains_for_modes",
    "TierEvaluation",
    "evaluate_tier_attribution",
    "validate_mode_evidence",
    "validate_attribution_manifest",
    "KVAdmissionDecision",
    "KVFlowLedger",
    "KVOperation",
    "KVTransferRequest",
    "KVVersion",
    "TorchKVBackend",
    "TorchKVCompletion",
    "CausalGateConfig",
    "CausalModeRecord",
    "CausalPromotion",
    "InferenceModeRecord",
    "evaluate_causal_matrix",
    "evaluate_inference_matrix",
    "DomainAdmissionController",
    "DomainBudget",
    "DomainDecision",
    "DomainRequest",
    "FlowAdmissionLedger",
    "AtlasEntry",
    "CounterSupport",
    "DomainEvidence",
    "DomainCoverage",
    "PathStatus",
    "assess_domain_coverage",
    "build_atlas",
    "controller_candidates",
    "detect_bottleneck_shift",
    "CounterDelta",
    "CounterSnapshot",
    "counter_delta",
    "validate_counter_series",
    "PathInterventionEvidence",
    "build_causal_domain_controller",
    "validate_path_intervention_artifact",
    "path_intervention_candidates",
    "controller_ready_domains",
    "checkpoint_state_flow",
    "kv_state_flow",
    "flow_route_signature",
    "StateFlowAdmission",
    "InferenceReplicationBlock",
    "ReplicationResult",
    "TrainingReplicationBlock",
    "evaluate_inference_replication",
    "evaluate_training_replication",
    "validate_foreground_path",
    "ObservationInterval",
    "JoinedObservationWindow",
    "canonicalize_observation_windows",
    "join_observation_window",
    "observation_window_contract",
    "serialize_joined_observation_window",
    "serialize_observation_interval",
    "validate_observation_windows",
]
